### ISSUE TITLE
esfs aborts with error code -11

### ISSUE THREAD

**Issue by walec51** [csirmaz/ESFS#1]
Hi, I've tried to build esfs on a fresh Debian 7 machine.
Unfortunately the resulting exec always aborts.

```
root@backup-serwer:~# cd ESFS-1.0.0-beta.7/

root@backup-serwer:~/ESFS-1.0.0-beta.7# perl Makefile.PL 

root@backup-serwer:~/ESFS-1.0.0-beta.7# make
./compile.pl < esfs.c > esfs_c.c
./compile.pl < params.h > params_c.h
./compile.pl < types.h > types_c.h
./compile.pl < snapshot.c > snapshot_c.c
./compile.pl < mfd.c > mfd_c.c
./compile.pl < block.c > block_c.c
./compile.pl < util.c > util_c.c
./compile.pl < util_locking.c > util_locking_c.c
./compile.pl < mflock.c > mflock_c.c
./compile.pl < fuse_fd_close.c > fuse_fd_close_c.c
./compile.pl < fuse_fd_read.c > fuse_fd_read_c.c
./compile.pl < fuse_fd_write.c > fuse_fd_write_c.c
./compile.pl < fuse_path_open.c > fuse_path_open_c.c
./compile.pl < fuse_path_read.c > fuse_path_read_c.c
./compile.pl < fuse_path_write.c > fuse_path_write_c.c
gcc -O3 -Wall `pkg-config fuse --cflags` -c esfs_c.c
In file included from esfs_c.c:68:0:
fuse_fd_close_c.c: In function ‘esfs_flush’:
fuse_fd_close_c.c:65:4: warning: variable ‘fsdata’ set but not used [-Wunused-but-set-variable]
fuse_fd_close_c.c: In function ‘esfs_release’:
fuse_fd_close_c.c:90:4: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
fuse_fd_close_c.c: In function ‘esfs_fsync’:
fuse_fd_close_c.c:126:4: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
fuse_fd_close_c.c: In function ‘esfs_releasedir’:
fuse_fd_close_c.c:163:4: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
fuse_fd_close_c.c: In function ‘esfs_fsyncdir’:
fuse_fd_close_c.c:200:4: warning: variable ‘fsdata’ set but not used [-Wunused-but-set-variable]
In file included from esfs_c.c:69:0:
fuse_fd_read_c.c: In function ‘esfs_read’:
fuse_fd_read_c.c:58:4: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
In file included from esfs_c.c:69:0:
fuse_fd_read_c.c: In function ‘esfs_readdir’:
fuse_fd_read_c.c:327:4: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
fuse_fd_read_c.c: In function ‘esfs_fgetattr’:
fuse_fd_read_c.c:410:4: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
fuse_fd_read_c.c:410:4: warning: variable ‘fsdata’ set but not used [-Wunused-but-set-variable]
In file included from esfs_c.c:70:0:
fuse_fd_write_c.c: In function ‘esfs_write’:
fuse_fd_write_c.c:58:4: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
In file included from esfs_c.c:70:0:
fuse_fd_write_c.c: In function ‘esfs_ftruncate’:
fuse_fd_write_c.c:107:4: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
In file included from esfs_c.c:73:0:
fuse_path_write_c.c: In function ‘esfs_utimens’:
fuse_path_write_c.c:378:8: warning: unused variable ‘ret’ [-Wunused-variable]
gcc -O3 -o esfs esfs_c.o `pkg-config fuse --libs`

root@backup-serwer:~/ESFS-1.0.0-beta.7# cp esfs /usr/bin/

root@backup-serwer:~/ESFS-1.0.0-beta.7# su - fuse -c "esfs -h"
There's a problem with the parameters; ESFS needs to be recompiled. Code = -11. Aborting.
```

**Comment by csirmaz** [comment]
Hi,

Thanks for your message. It seems the types on your system are not as ESFS expects them. The error message means that the maximum file size allowed by the system (based on off_t) is larger than the one that would be allowed by the types used by ESFS. To fix this, please try changing the #define lines for $$BL_S to 262144 (2^18) and $$BL_SLOG to 18 in types.h, or to even higher values if needed. $$BL_S always needs to be 2 ^ $$BL_SLOG.

Another problem seems to be the "cast to pointer from integer of different size" messages. These are probably because ESFS casts fuse_file_info.fh (which is a uint64_t) to a pointer. Unfortunately, I'm not sure how to fix this. Can you let me know whether you use 32-bit or 64-bit kernel and libraries so that I could try to reproduce the issue?

I hope these help. Please don't forget that ESFS is still in beta and so it's not suitable for mission-critical applications.

**Comment by walec51** [comment]
Hi,

Thanks for the quick response. 

It's a 32 bit kernel. I've used debian-7.7.0-i386-netinst.iso/
More info:

```
root@backup-serwer:~# uname -a
Linux backup-serwer 3.2.0-4-686-pae #1 SMP Debian 3.2.63-2+deb7u1 i686 GNU/Linux
```

My libfuse-dev is at version 2.9.0-2+deb7u1

I changed types.h like you said to:

```
#define $$BL_S 262144
#define $$BL_SLOG 18
```

But still I got

```
There's a problem with the parameters; ESFS needs to be recompiled. Code = -11. Aborting.
```

Also tried with BL_SLOG=20 (BL_S calculated accordingly) and it didn't help.

I'm setting up a small rsync backup server so its noting critical. If you'd like I can give you a temporary account on it :o)

**Comment by csirmaz** [comment]
Hi,

I managed to set up a 32-bit Debian in a VM and I could reproduce the problem. I have now pushed a patch that should fix the error - could you please revert the local changes and update your codebase to 1.0.0-beta.8, and try again?

I also considered the warning the compiler issues about casting, but I believe the end result will actually be correct, so it should be safe to ignore it. (A pointer which is 4 bytes on a 32bit system is stored in a uint64_t FUSE sets up.)

Thanks!
Elod

**Comment by walec51** [comment]
Hi,

Thanks for the quick fix.

I've started to do some simple test but I think I don't understand to use esfs property.

One question: should I modify the files in the UNDERLYING_ROOT_DIR or in the MOUNTPOINT ?
so that the spanshots will preserve their contents

**Comment by csirmaz** [comment]
Hi,

You should be changing files in MOUNTPOINT. For example:

```
$ esfs root mnt
$ cd mnt
/mnt$ ls
snapshots
/mnt$ echo "hello" > test
/mnt$ mkdir snapshots/Save1
/mnt$ echo "hello" >> test
/mnt$ cat test
hello
hello
/mnt$ cat snapshots/Save1/test
hello
/mnt$
```

Hope this helps!

**Comment by walec51** [comment]
Ok, I followed your instruction and it went welll:

```
fuse@backup-serwer:~$ mkdir test
fuse@backup-serwer:~$ cd test/
fuse@backup-serwer:~/test$ mkdir root mnt
fuse@backup-serwer:~/test$ esfs root mnt
fuse@backup-serwer:~/test$ cd mnt/
fuse@backup-serwer:~/test/mnt$ ls
snapshots
fuse@backup-serwer:~/test/mnt$ echo "AAA" > file.txt
fuse@backup-serwer:~/test/mnt$ mkdir snapshots/snp1
fuse@backup-serwer:~/test/mnt$ echo "BBB" >> file.txt
fuse@backup-serwer:~/test/mnt$ cat file.txt 
AAA
BBB
fuse@backup-serwer:~/test/mnt$ cat snapshots/snp1/file.txt 
AAA
fuse@backup-serwer:~/test/mnt$ 
```

but then I've tried to edit the file in vim

```
fuse@backup-serwer:~/test/mnt$ vim file.txt
```

inserted some 'x' characters in the middle

```
AAA
xxx
BBB
```

and when tried to save it using shift+ZZ - the terminal froze up

now every time I try to access that mount point from any other terminal

```
fuse@backup-serwer:~$ cd test/mnt
fuse@backup-serwer:~$ ls
```

It also freezes.

**Comment by csirmaz** [comment]
Hi,

You should be able to kill -9 the esfs process, and then umount the filesystem using fusermount.

vim appears to fail because it renames the file to be saved, and there may be a problem in the renaming logic. I will try to test and fix this as soon as I can.

**Comment by csirmaz** [comment]
Hi,
Thanks for spotting this problem. I've drafted fixes to a couple of issues in ESFS; however, the way renames are stored will need to be modified to ensure that it works properly in all cases. I'm not sure how long it will take, but I'm working on it.

**Comment by csirmaz** [comment]
Hi,

Sorry for the delay in responding to this issue. I have drafted a new way of storing renames to solve this problem, but to ensure correctness this information needs to be stored in a new data structure independent of the file handles. Implementing this will unfortunately take some time, so in order to be able to release a working version of ESFS, I removed support for renaming for now.

However, if files in ESFS are used as block (loop) devices for other filesystems, renames are not actually needed, and the resulting filesystem is also much faster than using ESFS directly. Please see the wiki as to how to do this.

I hope this helps, and thanks again for your patience.

Elod
