### ISSUE TITLE
Could you remove snapshot readonly?

### ISSUE THREAD

**Issue by oracleloyall** [csirmaz/ESFS#3]

**Comment by csirmaz** [comment]
Hi, thanks for your question. The fact that snapshots are read-only is inherent in how the data is stored, so unfortunately this will not be possible without a complete rewrite.

**Comment by oracleloyall** [comment]
> Hi, thanks for your question. The fact that snapshots are read-only is inherent in how the data is stored, so unfortunately this will not be possible without a complete rewrite.

If I want clone snapshot（like zfs clone base on snapshot），what can I do？

**Comment by csirmaz** [comment]
This is unfortunately not supported as only the main filesystem is editable by design.
